### ISSUE TITLE
Add password check on sign-up page

### ISSUE THREAD

**Issue by K-Straiton** [K-Straiton/CITS3403-Project#22]
Add a client side check on the sign-up page to check if both Password and Confirm Password fields have the same value before sending data to server.

**Comment by Sebagabones** [comment]
Seems like this is no longer needed - checking on the front end does have some benefits but it will still need to be done in the back-end every time a user submits the signup form anyway, so not really needed :) - closing this issue now :)

**Comment by Sebagabones** [comment]
Whoops - yeah we need to do this for the project, reopening it
